-- Demo catalog đa thương hiệu (8 brand, ≥40 SP có ảnh) cho môi trường demo/prod.
-- Idempotent + chống xung đột: chỉ chèn khi CHƯA tồn tại (theo unique). KHÔNG đụng SP Pancake.
-- Sinh tự động từ seed.ts (prisma/seed.ts) — nguồn canonical vẫn là seed.ts.

-- categories: 7 dòng
INSERT INTO categories ("id", "parentId", "name", "slug", "image", "sortOrder")
SELECT 'cat-baby', NULL, 'Cho bé', 'cho-be', NULL, 3
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE "id" = 'cat-baby' OR "slug" = 'cho-be');
INSERT INTO categories ("id", "parentId", "name", "slug", "image", "sortOrder")
SELECT 'cat-cleaning', NULL, 'Tẩy rửa sinh học', 'tay-rua-sinh-hoc', NULL, 2
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE "id" = 'cat-cleaning' OR "slug" = 'tay-rua-sinh-hoc');
INSERT INTO categories ("id", "parentId", "name", "slug", "image", "sortOrder")
SELECT 'cat-coffee', NULL, 'Cà phê & Đồ uống', 'ca-phe-do-uong', NULL, 6
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE "id" = 'cat-coffee' OR "slug" = 'ca-phe-do-uong');
INSERT INTO categories ("id", "parentId", "name", "slug", "image", "sortOrder")
SELECT 'cat-food', NULL, 'Nông sản & Thực phẩm', 'nong-san-thuc-pham', NULL, 7
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE "id" = 'cat-food' OR "slug" = 'nong-san-thuc-pham');
INSERT INTO categories ("id", "parentId", "name", "slug", "image", "sortOrder")
SELECT 'cat-mom', NULL, 'Cho mẹ bầu', 'cho-me-bau', NULL, 4
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE "id" = 'cat-mom' OR "slug" = 'cho-me-bau');
INSERT INTO categories ("id", "parentId", "name", "slug", "image", "sortOrder")
SELECT 'cat-personal', NULL, 'Chăm sóc cá nhân', 'cham-soc-ca-nhan', NULL, 5
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE "id" = 'cat-personal' OR "slug" = 'cham-soc-ca-nhan');
INSERT INTO categories ("id", "parentId", "name", "slug", "image", "sortOrder")
SELECT 'cat-skincare', NULL, 'Mỹ phẩm thiên nhiên', 'my-pham-thien-nhien', NULL, 1
WHERE NOT EXISTS (SELECT 1 FROM categories WHERE "id" = 'cat-skincare' OR "slug" = 'my-pham-thien-nhien');

-- products: 44 dòng
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-bhnong-cagaileo', 'seed-p-bhnong-cagaileo', 'BH.Nong', 'cao-ca-gai-leo-bhnong', 'Cao cà gai leo BH.Nong', 'Hỗ trợ mát gan, giải độc tự nhiên.', 'Hỗ trợ mát gan, giải độc tự nhiên.', ARRAY['https://picsum.photos/seed/tubu-cao-ca-gai-leo-bhnong/800/800']::text[], 'https://picsum.photos/seed/tubu-cao-ca-gai-leo-bhnong/800/800', ARRAY['cat-food']::text[], ARRAY['bh.nong']::text[], TRUE, FALSE, FALSE, 220000, NULL, NULL, NULL, ARRAY['eco']::text[], NULL, ARRAY['OCOP']::text[], '2026-06-15T16:46:25.480Z', '2026-06-15T16:46:25.480Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-bhnong-cagaileo' OR "slug" = 'cao-ca-gai-leo-bhnong' OR "pancakeId" = 'seed-p-bhnong-cagaileo');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-bhnong-cashew', 'seed-p-bhnong-cashew', 'BH.Nong', 'hat-dieu-rang-moc-bhnong', 'Hạt điều rang mộc BH.Nong', 'Điều Bình Phước rang mộc, giòn bùi.', 'Điều Bình Phước rang mộc, giòn bùi.', ARRAY['https://picsum.photos/seed/tubu-hat-dieu-rang-moc-bhnong/800/800']::text[], 'https://picsum.photos/seed/tubu-hat-dieu-rang-moc-bhnong/800/800', ARRAY['cat-food']::text[], ARRAY['bh.nong']::text[], TRUE, FALSE, FALSE, 180000, 159000, NULL, NULL, ARRAY['eco']::text[], NULL, ARRAY['OCOP']::text[], '2026-06-15T16:45:21.303Z', '2026-06-15T16:46:25.415Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-bhnong-cashew' OR "slug" = 'hat-dieu-rang-moc-bhnong' OR "pancakeId" = 'seed-p-bhnong-cashew');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-bhnong-honey', 'seed-p-bhnong-honey', 'BH.Nong', 'mat-ong-rung-bhnong', 'Mật ong rừng nguyên chất BH.Nong', 'Mật ong rừng tự nhiên, không pha đường.', 'Mật ong rừng tự nhiên, không pha đường.', ARRAY['https://picsum.photos/seed/tubu-mat-ong-rung-bhnong/800/800']::text[], 'https://picsum.photos/seed/tubu-mat-ong-rung-bhnong/800/800', ARRAY['cat-food']::text[], ARRAY['bh.nong']::text[], TRUE, TRUE, FALSE, 260000, NULL, NULL, NULL, ARRAY['eco']::text[], NULL, ARRAY['Nguyên chất 100%']::text[], '2026-06-15T16:45:21.298Z', '2026-06-15T16:46:25.412Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-bhnong-honey' OR "slug" = 'mat-ong-rung-bhnong' OR "pancakeId" = 'seed-p-bhnong-honey');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-bhnong-pepper', 'seed-p-bhnong-pepper', 'BH.Nong', 'tieu-den-bhnong', 'Tiêu đen Chư Sê BH.Nong', 'Tiêu Tây Nguyên thơm nồng, hạt chắc.', 'Tiêu Tây Nguyên thơm nồng, hạt chắc.', ARRAY['https://picsum.photos/seed/tubu-tieu-den-bhnong/800/800']::text[], 'https://picsum.photos/seed/tubu-tieu-den-bhnong/800/800', ARRAY['cat-food']::text[], ARRAY['bh.nong']::text[], TRUE, FALSE, FALSE, 95000, NULL, NULL, NULL, ARRAY['eco']::text[], NULL, ARRAY['OCOP']::text[], '2026-06-15T16:45:21.306Z', '2026-06-15T16:46:25.420Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-bhnong-pepper' OR "slug" = 'tieu-den-bhnong' OR "pancakeId" = 'seed-p-bhnong-pepper');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-bhnong-tea', 'seed-p-bhnong-tea', 'BH.Nong', 'tra-thao-moc-bhnong', 'Trà thảo mộc thanh nhiệt BH.Nong', 'Atiso, cúc, cam thảo — thanh mát mỗi ngày.', 'Atiso, cúc, cam thảo — thanh mát mỗi ngày.', ARRAY['https://picsum.photos/seed/tubu-tra-thao-moc-bhnong/800/800']::text[], 'https://picsum.photos/seed/tubu-tra-thao-moc-bhnong/800/800', ARRAY['cat-food']::text[], ARRAY['bh.nong']::text[], TRUE, FALSE, FALSE, 85000, NULL, NULL, NULL, ARRAY['eco']::text[], NULL, ARRAY['Vegan']::text[], '2026-06-15T16:45:21.309Z', '2026-06-15T16:46:25.424Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-bhnong-tea' OR "slug" = 'tra-thao-moc-bhnong' OR "pancakeId" = 'seed-p-bhnong-tea');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-cobote-diapercream', 'seed-p-cobote-diapercream', 'Cobote', 'kem-chong-ham-cobote', 'Kem chống hăm Cobote', 'Làm dịu, phục hồi vùng da hăm của bé.', 'Làm dịu, phục hồi vùng da hăm của bé.', ARRAY['https://picsum.photos/seed/tubu-kem-chong-ham-cobote/800/800']::text[], 'https://picsum.photos/seed/tubu-kem-chong-ham-cobote/800/800', ARRAY['cat-baby']::text[], ARRAY['cobote']::text[], TRUE, FALSE, FALSE, 119000, NULL, NULL, NULL, ARRAY['mom_baby']::text[], NULL, ARRAY['Vegan']::text[], '2026-06-15T16:45:21.278Z', '2026-06-15T16:46:25.391Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-cobote-diapercream' OR "slug" = 'kem-chong-ham-cobote' OR "pancakeId" = 'seed-p-cobote-diapercream');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-cobote-massage', 'seed-p-cobote-massage', 'Cobote', 'dau-massage-be-cobote', 'Dầu massage cho bé Cobote', 'Dưỡng da bé mềm mại, hỗ trợ giấc ngủ.', 'Dưỡng da bé mềm mại, hỗ trợ giấc ngủ.', ARRAY['https://picsum.photos/seed/tubu-dau-massage-be-cobote/800/800']::text[], 'https://picsum.photos/seed/tubu-dau-massage-be-cobote/800/800', ARRAY['cat-baby']::text[], ARRAY['cobote']::text[], TRUE, FALSE, FALSE, 109000, NULL, NULL, NULL, ARRAY['mom_baby']::text[], NULL, ARRAY['Vegan']::text[], '2026-06-15T16:46:25.473Z', '2026-06-15T16:46:25.473Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-cobote-massage' OR "slug" = 'dau-massage-be-cobote' OR "pancakeId" = 'seed-p-cobote-massage');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-cobote-powder', 'seed-p-cobote-powder', 'Cobote', 'phan-rom-thao-duoc-cobote', 'Phấn rôm thảo dược Cobote', 'Hút ẩm, ngừa hăm, không bột talc.', 'Hút ẩm, ngừa hăm, không bột talc.', ARRAY['https://picsum.photos/seed/tubu-phan-rom-thao-duoc-cobote/800/800']::text[], 'https://picsum.photos/seed/tubu-phan-rom-thao-duoc-cobote/800/800', ARRAY['cat-baby']::text[], ARRAY['cobote']::text[], TRUE, FALSE, FALSE, 79000, NULL, NULL, NULL, ARRAY['mom_baby']::text[], NULL, ARRAY['Talc-free']::text[], '2026-06-15T16:45:21.275Z', '2026-06-15T16:46:25.387Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-cobote-powder' OR "slug" = 'phan-rom-thao-duoc-cobote' OR "pancakeId" = 'seed-p-cobote-powder');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-cobote-tram', 'seed-p-cobote-tram', 'Cobote', 'dau-tram-be-cobote', 'Dầu tràm cho bé Cobote', 'Giữ ấm, phòng ho cảm cho bé sơ sinh.', 'Giữ ấm, phòng ho cảm cho bé sơ sinh.', ARRAY['https://picsum.photos/seed/tubu-dau-tram-be-cobote/800/800']::text[], 'https://picsum.photos/seed/tubu-dau-tram-be-cobote/800/800', ARRAY['cat-baby']::text[], ARRAY['cobote']::text[], TRUE, TRUE, FALSE, 89000, NULL, NULL, NULL, ARRAY['mom_baby']::text[], '[{"name":"Tinh dầu tràm Huế","benefit":"Giữ ấm, kháng khuẩn đường hô hấp","percentage":"100%"}]'::jsonb, ARRAY['Nguyên chất 100%']::text[], '2026-06-15T16:45:21.269Z', '2026-06-15T16:46:25.379Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-cobote-tram' OR "slug" = 'dau-tram-be-cobote' OR "pancakeId" = 'seed-p-cobote-tram');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-cobote-wash', 'seed-p-cobote-wash', 'Cobote', 'nuoc-tam-goi-be-cobote', 'Nước tắm gội thảo dược cho bé Cobote', 'Tắm gội 2 trong 1, không cay mắt bé.', 'Tắm gội 2 trong 1, không cay mắt bé.', ARRAY['https://picsum.photos/seed/tubu-nuoc-tam-goi-be-cobote/800/800']::text[], 'https://picsum.photos/seed/tubu-nuoc-tam-goi-be-cobote/800/800', ARRAY['cat-baby']::text[], ARRAY['cobote']::text[], TRUE, FALSE, FALSE, 155000, 132000, NULL, NULL, ARRAY['mom_baby']::text[], NULL, ARRAY['Vegan']::text[], '2026-06-15T16:45:21.272Z', '2026-06-15T16:46:25.382Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-cobote-wash' OR "slug" = 'nuoc-tam-goi-be-cobote' OR "pancakeId" = 'seed-p-cobote-wash');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-fuwa-bottle', 'seed-p-fuwa-bottle', 'Fuwa3e', 'nuoc-rua-binh-sua-fuwa3e', 'Nước rửa bình sữa Fuwa3e', 'An toàn cho bé, sạch cặn sữa, không mùi.', 'An toàn cho bé, sạch cặn sữa, không mùi.', ARRAY['https://picsum.photos/seed/tubu-nuoc-rua-binh-sua-fuwa3e/800/800']::text[], 'https://picsum.photos/seed/tubu-nuoc-rua-binh-sua-fuwa3e/800/800', ARRAY['cat-cleaning','cat-baby']::text[], ARRAY['fuwa3e']::text[], TRUE, FALSE, FALSE, 135000, NULL, NULL, NULL, ARRAY['mom_baby']::text[], NULL, ARRAY['Eco','Food-grade']::text[], '2026-06-15T16:45:21.264Z', '2026-06-15T16:46:25.375Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-fuwa-bottle' OR "slug" = 'nuoc-rua-binh-sua-fuwa3e' OR "pancakeId" = 'seed-p-fuwa-bottle');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-fuwa-dishwash', 'seed-p-fuwa-dishwash', 'Fuwa3e', 'nuoc-rua-chen-fuwa3e', 'Nước rửa chén sinh học Fuwa3e', 'Lên men enzyme dứa, an toàn cho da tay.', 'Lên men enzyme dứa, an toàn cho da tay.', ARRAY['https://picsum.photos/seed/tubu-nuoc-rua-chen-fuwa3e/800/800']::text[], 'https://picsum.photos/seed/tubu-nuoc-rua-chen-fuwa3e/800/800', ARRAY['cat-cleaning']::text[], ARRAY['fuwa3e']::text[], TRUE, TRUE, FALSE, 120000, NULL, NULL, NULL, ARRAY['home_clean']::text[], '[{"name":"Enzyme dứa lên men","benefit":"Phân giải dầu mỡ, không hại da tay","percentage":"15%"},{"name":"Tinh dầu sả","benefit":"Khử mùi tanh, kháng khuẩn tự nhiên"},{"name":"Nước cất","benefit":"Dung môi an toàn, phân huỷ sinh học"}]'::jsonb, ARRAY['Eco']::text[], '2026-06-15T16:40:37.334Z', '2026-06-15T16:46:25.359Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-fuwa-dishwash' OR "slug" = 'nuoc-rua-chen-fuwa3e' OR "pancakeId" = 'seed-p-fuwa-dishwash');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-fuwa-floor', 'seed-p-fuwa-floor', 'Fuwa3e', 'nuoc-lau-san-fuwa3e', 'Nước lau sàn enzyme Fuwa3e', 'Sàn sạch bóng, hương thảo mộc dịu.', 'Sàn sạch bóng, hương thảo mộc dịu.', ARRAY['https://picsum.photos/seed/tubu-nuoc-lau-san-fuwa3e/800/800']::text[], 'https://picsum.photos/seed/tubu-nuoc-lau-san-fuwa3e/800/800', ARRAY['cat-cleaning']::text[], ARRAY['fuwa3e']::text[], TRUE, FALSE, FALSE, 165000, 139000, NULL, NULL, ARRAY['home_clean']::text[], NULL, ARRAY['Eco']::text[], '2026-06-15T16:45:21.257Z', '2026-06-15T16:46:25.368Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-fuwa-floor' OR "slug" = 'nuoc-lau-san-fuwa3e' OR "pancakeId" = 'seed-p-fuwa-floor');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-fuwa-glass', 'seed-p-fuwa-glass', 'Fuwa3e', 'nuoc-lau-kinh-fuwa3e', 'Nước lau kính enzyme Fuwa3e', 'Sáng bóng không vệt, không amoniac.', 'Sáng bóng không vệt, không amoniac.', ARRAY['https://picsum.photos/seed/tubu-nuoc-lau-kinh-fuwa3e/800/800']::text[], 'https://picsum.photos/seed/tubu-nuoc-lau-kinh-fuwa3e/800/800', ARRAY['cat-cleaning']::text[], ARRAY['fuwa3e']::text[], TRUE, FALSE, FALSE, 79000, NULL, NULL, NULL, ARRAY['home_clean']::text[], NULL, ARRAY['Eco']::text[], '2026-06-15T16:46:25.470Z', '2026-06-15T16:46:25.470Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-fuwa-glass' OR "slug" = 'nuoc-lau-kinh-fuwa3e' OR "pancakeId" = 'seed-p-fuwa-glass');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-fuwa-handwash', 'seed-p-fuwa-handwash', 'Fuwa3e', 'nuoc-rua-tay-fuwa3e', 'Nước rửa tay sinh học Fuwa3e', 'Sạch khuẩn dịu nhẹ, dưỡng ẩm da tay.', 'Sạch khuẩn dịu nhẹ, dưỡng ẩm da tay.', ARRAY['https://picsum.photos/seed/tubu-nuoc-rua-tay-fuwa3e/800/800']::text[], 'https://picsum.photos/seed/tubu-nuoc-rua-tay-fuwa3e/800/800', ARRAY['cat-cleaning']::text[], ARRAY['fuwa3e']::text[], TRUE, FALSE, FALSE, 89000, NULL, NULL, NULL, ARRAY['home_clean','mom_baby']::text[], NULL, ARRAY['Eco']::text[], '2026-06-15T16:45:21.261Z', '2026-06-15T16:46:25.372Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-fuwa-handwash' OR "slug" = 'nuoc-rua-tay-fuwa3e' OR "pancakeId" = 'seed-p-fuwa-handwash');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-fuwa-laundry', 'seed-p-fuwa-laundry', 'Fuwa3e', 'nuoc-giat-fuwa3e', 'Nước giặt sinh học Fuwa3e', 'Sạch sâu, dịu nhẹ cho đồ em bé.', 'Sạch sâu, dịu nhẹ cho đồ em bé.', ARRAY['https://picsum.photos/seed/tubu-nuoc-giat-fuwa3e/800/800']::text[], 'https://picsum.photos/seed/tubu-nuoc-giat-fuwa3e/800/800', ARRAY['cat-cleaning','cat-baby']::text[], ARRAY['fuwa3e']::text[], TRUE, TRUE, FALSE, 210000, NULL, NULL, NULL, ARRAY['mom_baby','home_clean']::text[], NULL, ARRAY['Eco']::text[], '2026-06-15T16:40:37.344Z', '2026-06-15T16:46:25.364Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-fuwa-laundry' OR "slug" = 'nuoc-giat-fuwa3e' OR "pancakeId" = 'seed-p-fuwa-laundry');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-hector-clay', 'seed-p-hector-clay', 'Hector', 'sap-vuot-toc-hector', 'Sáp vuốt tóc Hector Matte', 'Giữ nếp tự nhiên cả ngày, không bóng nhờn.', 'Giữ nếp tự nhiên cả ngày, không bóng nhờn.', ARRAY['https://picsum.photos/seed/tubu-sap-vuot-toc-hector/800/800']::text[], 'https://picsum.photos/seed/tubu-sap-vuot-toc-hector/800/800', ARRAY['cat-personal']::text[], ARRAY['hector']::text[], TRUE, TRUE, FALSE, 160000, NULL, NULL, NULL, ARRAY['skincare']::text[], NULL, ARRAY[]::text[], '2026-06-15T16:45:21.327Z', '2026-06-15T16:46:25.441Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-hector-clay' OR "slug" = 'sap-vuot-toc-hector' OR "pancakeId" = 'seed-p-hector-clay');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-hector-deo', 'seed-p-hector-deo', 'Hector', 'lan-khu-mui-hector', 'Lăn khử mùi thiên nhiên Hector', 'Khử mùi 24h, không cồn, không nhôm.', 'Khử mùi 24h, không cồn, không nhôm.', ARRAY['https://picsum.photos/seed/tubu-lan-khu-mui-hector/800/800']::text[], 'https://picsum.photos/seed/tubu-lan-khu-mui-hector/800/800', ARRAY['cat-personal']::text[], ARRAY['hector']::text[], TRUE, FALSE, FALSE, 99000, NULL, NULL, NULL, ARRAY['skincare']::text[], NULL, ARRAY['Aluminum-free']::text[], '2026-06-15T16:45:21.338Z', '2026-06-15T16:46:25.451Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-hector-deo' OR "slug" = 'lan-khu-mui-hector' OR "pancakeId" = 'seed-p-hector-deo');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-hector-facewash', 'seed-p-hector-facewash', 'Hector', 'sua-rua-mat-than-tre-hector', 'Sữa rửa mặt than tre Hector', 'Sạch nhờn, sạch bụi mịn cho da nam.', 'Sạch nhờn, sạch bụi mịn cho da nam.', ARRAY['https://picsum.photos/seed/tubu-sua-rua-mat-than-tre-hector/800/800']::text[], 'https://picsum.photos/seed/tubu-sua-rua-mat-than-tre-hector/800/800', ARRAY['cat-personal','cat-skincare']::text[], ARRAY['hector']::text[], TRUE, FALSE, FALSE, 145000, 119000, NULL, NULL, ARRAY['skincare']::text[], NULL, ARRAY['Vegan']::text[], '2026-06-15T16:45:21.330Z', '2026-06-15T16:46:25.444Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-hector-facewash' OR "slug" = 'sua-rua-mat-than-tre-hector' OR "pancakeId" = 'seed-p-hector-facewash');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-hector-shampoo', 'seed-p-hector-shampoo', 'Hector', 'dau-goi-bac-ha-hector', 'Dầu gội bạc hà mát lạnh Hector', 'Sảng khoái, sạch gàu, mát da đầu.', 'Sảng khoái, sạch gàu, mát da đầu.', ARRAY['https://picsum.photos/seed/tubu-dau-goi-bac-ha-hector/800/800']::text[], 'https://picsum.photos/seed/tubu-dau-goi-bac-ha-hector/800/800', ARRAY['cat-personal']::text[], ARRAY['hector']::text[], TRUE, FALSE, FALSE, 135000, NULL, NULL, NULL, ARRAY['skincare']::text[], NULL, ARRAY['Vegan']::text[], '2026-06-15T16:45:21.334Z', '2026-06-15T16:46:25.447Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-hector-shampoo' OR "slug" = 'dau-goi-bac-ha-hector' OR "pancakeId" = 'seed-p-hector-shampoo');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-leplateau-arabica', 'seed-p-leplateau-arabica', 'Le Plateau Coffee', 'arabica-cau-dat-le-plateau', 'Cà phê Arabica Cầu Đất Le Plateau', 'Hạt rang specialty, hậu vị trái cây, chua thanh.', 'Hạt rang specialty, hậu vị trái cây, chua thanh.', ARRAY['https://picsum.photos/seed/tubu-arabica-cau-dat-le-plateau/800/800']::text[], 'https://picsum.photos/seed/tubu-arabica-cau-dat-le-plateau/800/800', ARRAY['cat-coffee','cat-food']::text[], ARRAY['le plateau coffee']::text[], TRUE, TRUE, FALSE, 185000, NULL, NULL, NULL, ARRAY['eco']::text[], '[{"name":"Arabica Cầu Đất 1.650m","benefit":"Hương hoa, hậu vị cam quýt","percentage":"100%"}]'::jsonb, ARRAY['Specialty','Rainforest Alliance']::text[], '2026-06-15T16:45:21.282Z', '2026-06-15T16:46:25.394Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-leplateau-arabica' OR "slug" = 'arabica-cau-dat-le-plateau' OR "pancakeId" = 'seed-p-leplateau-arabica');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-leplateau-coldbrew', 'seed-p-leplateau-coldbrew', 'Le Plateau Coffee', 'cold-brew-tui-loc-le-plateau', 'Cold Brew túi lọc Le Plateau', 'Ủ lạnh 12h, ngọt dịu, ít axit.', 'Ủ lạnh 12h, ngọt dịu, ít axit.', ARRAY['https://picsum.photos/seed/tubu-cold-brew-tui-loc-le-plateau/800/800']::text[], 'https://picsum.photos/seed/tubu-cold-brew-tui-loc-le-plateau/800/800', ARRAY['cat-coffee']::text[], ARRAY['le plateau coffee']::text[], TRUE, FALSE, FALSE, 120000, NULL, NULL, NULL, ARRAY['eco']::text[], NULL, ARRAY[]::text[], '2026-06-15T16:45:21.295Z', '2026-06-15T16:46:25.408Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-leplateau-coldbrew' OR "slug" = 'cold-brew-tui-loc-le-plateau' OR "pancakeId" = 'seed-p-leplateau-coldbrew');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-leplateau-drip', 'seed-p-leplateau-drip', 'Le Plateau Coffee', 'ca-phe-phin-giay-le-plateau', 'Cà phê phin giấy Le Plateau (hộp 10)', 'Pha nhanh tại bàn, tiện mang đi.', 'Pha nhanh tại bàn, tiện mang đi.', ARRAY['https://picsum.photos/seed/tubu-ca-phe-phin-giay-le-plateau/800/800']::text[], 'https://picsum.photos/seed/tubu-ca-phe-phin-giay-le-plateau/800/800', ARRAY['cat-coffee']::text[], ARRAY['le plateau coffee']::text[], TRUE, FALSE, FALSE, 95000, NULL, NULL, NULL, ARRAY['eco']::text[], NULL, ARRAY[]::text[], '2026-06-15T16:45:21.291Z', '2026-06-15T16:46:25.405Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-leplateau-drip' OR "slug" = 'ca-phe-phin-giay-le-plateau' OR "pancakeId" = 'seed-p-leplateau-drip');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-leplateau-instant', 'seed-p-leplateau-instant', 'Le Plateau Coffee', 'ca-phe-sua-hoa-tan-le-plateau', 'Cà phê sữa hoà tan Le Plateau (hộp 12)', 'Cà phê sữa 3in1 từ hạt thật, tiện lợi.', 'Cà phê sữa 3in1 từ hạt thật, tiện lợi.', ARRAY['https://picsum.photos/seed/tubu-ca-phe-sua-hoa-tan-le-plateau/800/800']::text[], 'https://picsum.photos/seed/tubu-ca-phe-sua-hoa-tan-le-plateau/800/800', ARRAY['cat-coffee']::text[], ARRAY['le plateau coffee']::text[], TRUE, FALSE, FALSE, 89000, 75000, NULL, NULL, ARRAY['eco']::text[], NULL, ARRAY[]::text[], '2026-06-15T16:46:25.476Z', '2026-06-15T16:46:25.476Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-leplateau-instant' OR "slug" = 'ca-phe-sua-hoa-tan-le-plateau' OR "pancakeId" = 'seed-p-leplateau-instant');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-leplateau-robusta', 'seed-p-leplateau-robusta', 'Le Plateau Coffee', 'robusta-honey-le-plateau', 'Cà phê Robusta Honey Le Plateau', 'Sơ chế honey, đậm vị, ít đắng gắt.', 'Sơ chế honey, đậm vị, ít đắng gắt.', ARRAY['https://picsum.photos/seed/tubu-robusta-honey-le-plateau/800/800']::text[], 'https://picsum.photos/seed/tubu-robusta-honey-le-plateau/800/800', ARRAY['cat-coffee','cat-food']::text[], ARRAY['le plateau coffee']::text[], TRUE, TRUE, FALSE, 145000, 125000, NULL, NULL, ARRAY['eco']::text[], NULL, ARRAY['Honey process']::text[], '2026-06-15T16:45:21.288Z', '2026-06-15T16:46:25.399Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-leplateau-robusta' OR "slug" = 'robusta-honey-le-plateau' OR "pancakeId" = 'seed-p-leplateau-robusta');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-polang-bodywash', 'seed-p-polang-bodywash', 'Pơ Lang', 'sua-tam-sa-po-lang', 'Sữa tắm sả chanh Pơ Lang', 'Hương sả chanh thư giãn, dưỡng ẩm.', 'Hương sả chanh thư giãn, dưỡng ẩm.', ARRAY['https://picsum.photos/seed/tubu-sua-tam-sa-po-lang/800/800']::text[], 'https://picsum.photos/seed/tubu-sua-tam-sa-po-lang/800/800', ARRAY['cat-skincare','cat-personal']::text[], ARRAY['pơ lang']::text[], TRUE, FALSE, FALSE, 175000, NULL, NULL, NULL, ARRAY['skincare']::text[], NULL, ARRAY['Vegan']::text[], '2026-06-15T16:40:37.348Z', '2026-06-15T16:46:25.335Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-polang-bodywash' OR "slug" = 'sua-tam-sa-po-lang' OR "pancakeId" = 'seed-p-polang-bodywash');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-polang-facemist', 'seed-p-polang-facemist', 'Pơ Lang', 'xit-khoang-hoa-hong-po-lang', 'Xịt khoáng hoa hồng Pơ Lang', 'Cấp ẩm tức thì, làm dịu da căng thẳng.', 'Cấp ẩm tức thì, làm dịu da căng thẳng.', ARRAY['https://picsum.photos/seed/tubu-xit-khoang-hoa-hong-po-lang/800/800']::text[], 'https://picsum.photos/seed/tubu-xit-khoang-hoa-hong-po-lang/800/800', ARRAY['cat-skincare']::text[], ARRAY['pơ lang']::text[], TRUE, FALSE, FALSE, 145000, NULL, NULL, NULL, ARRAY['skincare']::text[], NULL, ARRAY['Vegan']::text[], '2026-06-15T16:45:21.244Z', '2026-06-15T16:46:25.356Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-polang-facemist' OR "slug" = 'xit-khoang-hoa-hong-po-lang' OR "pancakeId" = 'seed-p-polang-facemist');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-polang-ginger', 'seed-p-polang-ginger', 'Pơ Lang', 'dau-gung-po-lang', 'Dầu gừng massage Pơ Lang', 'Làm ấm, thư giãn cơ sau ngày dài.', 'Làm ấm, thư giãn cơ sau ngày dài.', ARRAY['https://picsum.photos/seed/tubu-dau-gung-po-lang/800/800']::text[], 'https://picsum.photos/seed/tubu-dau-gung-po-lang/800/800', ARRAY['cat-personal']::text[], ARRAY['pơ lang']::text[], TRUE, TRUE, FALSE, 135000, 115000, NULL, NULL, ARRAY['eco']::text[], NULL, ARRAY['Handmade']::text[], '2026-06-15T16:45:21.236Z', '2026-06-15T16:46:25.339Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-polang-ginger' OR "slug" = 'dau-gung-po-lang' OR "pancakeId" = 'seed-p-polang-ginger');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-polang-hairoil', 'seed-p-polang-hairoil', 'Pơ Lang', 'dau-duong-toc-bo-ket-po-lang', 'Dầu dưỡng tóc bồ kết Pơ Lang', 'Phục hồi tóc khô xơ, vào nếp mượt.', 'Phục hồi tóc khô xơ, vào nếp mượt.', ARRAY['https://picsum.photos/seed/tubu-dau-duong-toc-bo-ket-po-lang/800/800']::text[], 'https://picsum.photos/seed/tubu-dau-duong-toc-bo-ket-po-lang/800/800', ARRAY['cat-personal']::text[], ARRAY['pơ lang']::text[], TRUE, FALSE, FALSE, 125000, NULL, NULL, NULL, ARRAY['skincare']::text[], NULL, ARRAY['Handmade']::text[], '2026-06-15T16:46:25.464Z', '2026-06-15T16:46:25.464Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-polang-hairoil' OR "slug" = 'dau-duong-toc-bo-ket-po-lang' OR "pancakeId" = 'seed-p-polang-hairoil');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-polang-lemongrass', 'seed-p-polang-lemongrass', 'Pơ Lang', 'tinh-dau-sa-chanh-po-lang', 'Tinh dầu sả chanh Pơ Lang', 'Đuổi muỗi, khử mùi, thư giãn không gian.', 'Đuổi muỗi, khử mùi, thư giãn không gian.', ARRAY['https://picsum.photos/seed/tubu-tinh-dau-sa-chanh-po-lang/800/800']::text[], 'https://picsum.photos/seed/tubu-tinh-dau-sa-chanh-po-lang/800/800', ARRAY['cat-personal']::text[], ARRAY['pơ lang']::text[], TRUE, FALSE, FALSE, 110000, NULL, NULL, NULL, ARRAY['eco','home_clean']::text[], NULL, ARRAY['Nguyên chất 100%']::text[], '2026-06-15T16:45:21.241Z', '2026-06-15T16:46:25.351Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-polang-lemongrass' OR "slug" = 'tinh-dau-sa-chanh-po-lang' OR "pancakeId" = 'seed-p-polang-lemongrass');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-polang-shampoo', 'seed-p-polang-shampoo', 'Pơ Lang', 'dau-goi-buoi-po-lang', 'Dầu gội bưởi Pơ Lang', 'Dầu gội thảo dược tinh dầu bưởi, giảm rụng tóc.', 'Dầu gội thảo dược tinh dầu bưởi, giảm rụng tóc.', ARRAY['https://picsum.photos/seed/tubu-dau-goi-buoi-po-lang/800/800']::text[], 'https://picsum.photos/seed/tubu-dau-goi-buoi-po-lang/800/800', ARRAY['cat-skincare','cat-personal']::text[], ARRAY['pơ lang']::text[], TRUE, TRUE, FALSE, 165000, NULL, NULL, NULL, ARRAY['sensitive_skin','skincare']::text[], '[{"name":"Tinh dầu bưởi","benefit":"Kích thích mọc tóc, giảm gãy rụng","percentage":"2%"},{"name":"Bồ kết","benefit":"Làm sạch dịu nhẹ, sạch gàu tự nhiên"},{"name":"Hương nhu","benefit":"Thư giãn da đầu, mượt tóc"}]'::jsonb, ARRAY['Vegan']::text[], '2026-06-15T16:40:37.320Z', '2026-06-15T16:46:25.328Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-polang-shampoo' OR "slug" = 'dau-goi-buoi-po-lang' OR "pancakeId" = 'seed-p-polang-shampoo');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-sokfram-centella', 'seed-p-sokfram-centella', 'Sokfram', 'bot-rau-ma-sokfram', 'Bột rau má nguyên chất Sokfram', 'Sấy lạnh giữ dưỡng chất, pha uống tiện lợi.', 'Sấy lạnh giữ dưỡng chất, pha uống tiện lợi.', ARRAY['https://picsum.photos/seed/tubu-bot-rau-ma-sokfram/800/800']::text[], 'https://picsum.photos/seed/tubu-bot-rau-ma-sokfram/800/800', ARRAY['cat-food']::text[], ARRAY['sokfram']::text[], TRUE, FALSE, FALSE, 99000, NULL, NULL, NULL, ARRAY['eco']::text[], NULL, ARRAY['Organic']::text[], '2026-06-15T16:45:21.321Z', '2026-06-15T16:46:25.432Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-sokfram-centella' OR "slug" = 'bot-rau-ma-sokfram' OR "pancakeId" = 'seed-p-sokfram-centella');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-sokfram-chia', 'seed-p-sokfram-chia', 'Sokfram', 'hat-chia-uc-sokfram', 'Hạt chia Úc Sokfram', 'Giàu Omega-3 & chất xơ, pha uống tiện.', 'Giàu Omega-3 & chất xơ, pha uống tiện.', ARRAY['https://picsum.photos/seed/tubu-hat-chia-uc-sokfram/800/800']::text[], 'https://picsum.photos/seed/tubu-hat-chia-uc-sokfram/800/800', ARRAY['cat-food']::text[], ARRAY['sokfram']::text[], TRUE, FALSE, FALSE, 115000, NULL, NULL, NULL, ARRAY['eco']::text[], NULL, ARRAY['Organic']::text[], '2026-06-15T16:46:25.484Z', '2026-06-15T16:46:25.484Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-sokfram-chia' OR "slug" = 'hat-chia-uc-sokfram' OR "pancakeId" = 'seed-p-sokfram-chia');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-sokfram-coconut', 'seed-p-sokfram-coconut', 'Sokfram', 'dau-dua-ep-lanh-sokfram', 'Dầu dừa ép lạnh Sokfram', 'Ép lạnh nguyên chất, dùng ăn & dưỡng.', 'Ép lạnh nguyên chất, dùng ăn & dưỡng.', ARRAY['https://picsum.photos/seed/tubu-dau-dua-ep-lanh-sokfram/800/800']::text[], 'https://picsum.photos/seed/tubu-dau-dua-ep-lanh-sokfram/800/800', ARRAY['cat-food','cat-skincare']::text[], ARRAY['sokfram']::text[], TRUE, FALSE, FALSE, 130000, 110000, NULL, NULL, ARRAY['eco','skincare']::text[], NULL, ARRAY['Organic','Ép lạnh']::text[], '2026-06-15T16:45:21.316Z', '2026-06-15T16:46:25.429Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-sokfram-coconut' OR "slug" = 'dau-dua-ep-lanh-sokfram' OR "pancakeId" = 'seed-p-sokfram-coconut');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-sokfram-granola', 'seed-p-sokfram-granola', 'Sokfram', 'granola-hat-sokfram', 'Granola ngũ cốc hạt Sokfram', 'Ăn sáng healthy, ngọt nhẹ từ mật ong.', 'Ăn sáng healthy, ngọt nhẹ từ mật ong.', ARRAY['https://picsum.photos/seed/tubu-granola-hat-sokfram/800/800']::text[], 'https://picsum.photos/seed/tubu-granola-hat-sokfram/800/800', ARRAY['cat-food']::text[], ARRAY['sokfram']::text[], TRUE, FALSE, FALSE, 140000, NULL, NULL, NULL, ARRAY['eco']::text[], NULL, ARRAY['Không đường tinh luyện']::text[], '2026-06-15T16:45:21.324Z', '2026-06-15T16:46:25.438Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-sokfram-granola' OR "slug" = 'granola-hat-sokfram' OR "pancakeId" = 'seed-p-sokfram-granola');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-sokfram-rice', 'seed-p-sokfram-rice', 'Sokfram', 'gao-lut-huyet-rong-sokfram', 'Gạo lứt huyết rồng Sokfram', 'Gạo lứt đỏ giàu chất xơ, dẻo thơm.', 'Gạo lứt đỏ giàu chất xơ, dẻo thơm.', ARRAY['https://picsum.photos/seed/tubu-gao-lut-huyet-rong-sokfram/800/800']::text[], 'https://picsum.photos/seed/tubu-gao-lut-huyet-rong-sokfram/800/800', ARRAY['cat-food']::text[], ARRAY['sokfram']::text[], TRUE, TRUE, FALSE, 75000, NULL, NULL, NULL, ARRAY['eco']::text[], NULL, ARRAY['Organic']::text[], '2026-06-15T16:45:21.312Z', '2026-06-15T16:46:25.426Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-sokfram-rice' OR "slug" = 'gao-lut-huyet-rong-sokfram' OR "pancakeId" = 'seed-p-sokfram-rice');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-visante-cleanser', 'seed-p-visante-cleanser', 'Visante', 'nuoc-tay-trang-rau-ma-visante', 'Nước tẩy trang rau má Visante', 'Làm sạch dịu nhẹ, không lưu cồn.', 'Làm sạch dịu nhẹ, không lưu cồn.', ARRAY['https://picsum.photos/seed/tubu-nuoc-tay-trang-rau-ma-visante/800/800']::text[], 'https://picsum.photos/seed/tubu-nuoc-tay-trang-rau-ma-visante/800/800', ARRAY['cat-skincare']::text[], ARRAY['visante']::text[], TRUE, TRUE, FALSE, 180000, 155000, NULL, NULL, ARRAY['sensitive_skin','skincare']::text[], NULL, ARRAY['Vegan']::text[], '2026-06-15T16:45:21.211Z', '2026-06-15T16:46:25.309Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-visante-cleanser' OR "slug" = 'nuoc-tay-trang-rau-ma-visante' OR "pancakeId" = 'seed-p-visante-cleanser');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-visante-cream', 'seed-p-visante-cream', 'Visante', 'kem-duong-ba-bau-visante', 'Kem dưỡng cho mẹ bầu Visante', 'Ngừa rạn da, lành tính cho thai kỳ.', 'Ngừa rạn da, lành tính cho thai kỳ.', ARRAY['https://picsum.photos/seed/tubu-kem-duong-ba-bau-visante/800/800']::text[], 'https://picsum.photos/seed/tubu-kem-duong-ba-bau-visante/800/800', ARRAY['cat-mom']::text[], ARRAY['visante']::text[], TRUE, FALSE, FALSE, 290000, NULL, NULL, NULL, ARRAY['mom_baby']::text[], '[{"name":"Bơ hạt mỡ (Shea)","benefit":"Tăng đàn hồi, ngừa rạn da","percentage":"8%"},{"name":"Dầu jojoba","benefit":"Dưỡng ẩm sâu, thẩm thấu nhanh"}]'::jsonb, ARRAY['USDA Organic']::text[], '2026-06-15T16:40:37.352Z', '2026-06-15T16:46:25.304Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-visante-cream' OR "slug" = 'kem-duong-ba-bau-visante' OR "pancakeId" = 'seed-p-visante-cream');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-visante-eye', 'seed-p-visante-eye', 'Visante', 'kem-mat-rau-ma-visante', 'Kem mắt rau má Visante', 'Giảm bọng, mờ quầng thâm vùng mắt.', 'Giảm bọng, mờ quầng thâm vùng mắt.', ARRAY['https://picsum.photos/seed/tubu-kem-mat-rau-ma-visante/800/800']::text[], 'https://picsum.photos/seed/tubu-kem-mat-rau-ma-visante/800/800', ARRAY['cat-skincare']::text[], ARRAY['visante']::text[], TRUE, FALSE, FALSE, 295000, NULL, NULL, NULL, ARRAY['skincare']::text[], NULL, ARRAY['Vegan']::text[], '2026-06-15T16:46:25.461Z', '2026-06-15T16:46:25.461Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-visante-eye' OR "slug" = 'kem-mat-rau-ma-visante' OR "pancakeId" = 'seed-p-visante-eye');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-visante-lipbalm', 'seed-p-visante-lipbalm', 'Visante', 'son-duong-gac-visante', 'Son dưỡng gấc Visante', 'Dưỡng môi mềm mịn từ tinh dầu gấc.', 'Dưỡng môi mềm mịn từ tinh dầu gấc.', ARRAY['https://picsum.photos/seed/tubu-son-duong-gac-visante/800/800']::text[], 'https://picsum.photos/seed/tubu-son-duong-gac-visante/800/800', ARRAY['cat-skincare']::text[], ARRAY['visante']::text[], TRUE, FALSE, FALSE, 95000, 79000, NULL, NULL, ARRAY['skincare']::text[], NULL, ARRAY['Vegan']::text[], '2026-06-15T16:45:21.223Z', '2026-06-15T16:46:25.325Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-visante-lipbalm' OR "slug" = 'son-duong-gac-visante' OR "pancakeId" = 'seed-p-visante-lipbalm');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-visante-mask', 'seed-p-visante-mask', 'Visante', 'mat-na-rau-ma-visante', 'Mặt nạ rau má phục hồi Visante', 'Làm dịu da sau nắng, cấp ẩm tức thì.', 'Làm dịu da sau nắng, cấp ẩm tức thì.', ARRAY['https://picsum.photos/seed/tubu-mat-na-rau-ma-visante/800/800']::text[], 'https://picsum.photos/seed/tubu-mat-na-rau-ma-visante/800/800', ARRAY['cat-skincare']::text[], ARRAY['visante']::text[], TRUE, FALSE, FALSE, 25000, NULL, NULL, NULL, ARRAY['skincare']::text[], NULL, ARRAY['Vegan']::text[], '2026-06-15T16:45:21.220Z', '2026-06-15T16:46:25.320Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-visante-mask' OR "slug" = 'mat-na-rau-ma-visante' OR "pancakeId" = 'seed-p-visante-mask');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-visante-serum', 'seed-p-visante-serum', 'Visante', 'serum-duong-am-visante', 'Serum dưỡng ẩm Visante', 'Cấp ẩm chuyên sâu chiết xuất rau má.', 'Cấp ẩm chuyên sâu chiết xuất rau má.', ARRAY['https://picsum.photos/seed/tubu-serum-duong-am-visante/800/800']::text[], 'https://picsum.photos/seed/tubu-serum-duong-am-visante/800/800', ARRAY['cat-skincare']::text[], ARRAY['visante']::text[], TRUE, TRUE, FALSE, 320000, 289000, NULL, NULL, ARRAY['sensitive_skin','skincare']::text[], '[{"name":"Chiết xuất rau má","benefit":"Phục hồi, làm dịu da nhạy cảm","percentage":"5%"},{"name":"Hyaluronic Acid","benefit":"Cấp ẩm sâu, căng mịn","percentage":"2%"},{"name":"Chiết xuất lô hội","benefit":"Làm dịu, chống kích ứng"}]'::jsonb, ARRAY['USDA Organic','Vegan']::text[], '2026-06-15T16:40:37.341Z', '2026-06-15T16:46:25.294Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-visante-serum' OR "slug" = 'serum-duong-am-visante' OR "pancakeId" = 'seed-p-visante-serum');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-visante-sunscreen', 'seed-p-visante-sunscreen', 'Visante', 'kem-chong-nang-khoang-visante', 'Kem chống nắng khoáng Visante SPF50', 'Chống nắng vật lý, không gây bí da.', 'Chống nắng vật lý, không gây bí da.', ARRAY['https://picsum.photos/seed/tubu-kem-chong-nang-khoang-visante/800/800']::text[], 'https://picsum.photos/seed/tubu-kem-chong-nang-khoang-visante/800/800', ARRAY['cat-skincare']::text[], ARRAY['visante']::text[], TRUE, FALSE, FALSE, 345000, NULL, NULL, NULL, ARRAY['skincare']::text[], NULL, ARRAY['Reef-safe']::text[], '2026-06-15T16:45:21.215Z', '2026-06-15T16:46:25.314Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-visante-sunscreen' OR "slug" = 'kem-chong-nang-khoang-visante' OR "pancakeId" = 'seed-p-visante-sunscreen');
INSERT INTO products ("id", "pancakeId", "brand", "slug", "name", "description", "shortDesc", "images", "thumbnail", "categoryIds", "tags", "isActive", "isFeatured", "isCombo", "basePrice", "salePrice", "metaTitle", "metaDesc", "forSegment", "ingredients", "certifications", "createdAt", "updatedAt", "ratingAvg", "reviewCount")
SELECT 'p-visante-vitc', 'seed-p-visante-vitc', 'Visante', 'tinh-chat-vitamin-c-visante', 'Tinh chất Vitamin C Visante', 'Làm sáng, mờ thâm từ Vitamin C tự nhiên.', 'Làm sáng, mờ thâm từ Vitamin C tự nhiên.', ARRAY['https://picsum.photos/seed/tubu-tinh-chat-vitamin-c-visante/800/800']::text[], 'https://picsum.photos/seed/tubu-tinh-chat-vitamin-c-visante/800/800', ARRAY['cat-skincare']::text[], ARRAY['visante']::text[], TRUE, TRUE, FALSE, 380000, 329000, NULL, NULL, ARRAY['skincare']::text[], NULL, ARRAY['Vegan']::text[], '2026-06-15T16:46:25.456Z', '2026-06-15T16:46:25.456Z', 0, 0
WHERE NOT EXISTS (SELECT 1 FROM products WHERE "id" = 'p-visante-vitc' OR "slug" = 'tinh-chat-vitamin-c-visante' OR "pancakeId" = 'seed-p-visante-vitc');

-- variations: 48 dòng
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfuw9jj0001w1vfrccaij5o', 'seed-POLANG-SP-300', 'p-polang-shampoo', 'POLANG-SP-300', '300ml', '{"size":"300ml"}'::jsonb, 165000, NULL, NULL, NULL, 120, TRUE, 350
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfuw9jj0001w1vfrccaij5o' OR "sku" = 'POLANG-SP-300' OR "pancakeId" = 'seed-POLANG-SP-300');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfuw9jo0003w1vfvkx2j48l', 'seed-POLANG-SP-500', 'p-polang-shampoo', 'POLANG-SP-500', '500ml', '{"size":"500ml"}'::jsonb, 245000, 219000, NULL, NULL, 80, TRUE, 560
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfuw9jo0003w1vfvkx2j48l' OR "sku" = 'POLANG-SP-500' OR "pancakeId" = 'seed-POLANG-SP-500');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfuw9jt0005w1vfkndxukxy', 'seed-FUWA-DW-1L', 'p-fuwa-dishwash', 'FUWA-DW-1L', '1L', '{"size":"1L"}'::jsonb, 120000, NULL, NULL, NULL, 200, TRUE, 1050
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfuw9jt0005w1vfkndxukxy' OR "sku" = 'FUWA-DW-1L' OR "pancakeId" = 'seed-FUWA-DW-1L');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfuw9jv0007w1vfb1njbw7k', 'seed-FUWA-DW-5L', 'p-fuwa-dishwash', 'FUWA-DW-5L', 'Can 5L', '{"size":"5L"}'::jsonb, 480000, 430000, NULL, NULL, 40, TRUE, 5200
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfuw9jv0007w1vfb1njbw7k' OR "sku" = 'FUWA-DW-5L' OR "pancakeId" = 'seed-FUWA-DW-5L');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfuw9jy0009w1vfn8il35y6', 'seed-VIS-SR-30', 'p-visante-serum', 'VIS-SR-30', '30ml', '{"size":"30ml"}'::jsonb, 320000, 289000, NULL, NULL, 60, TRUE, 90
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfuw9jy0009w1vfn8il35y6' OR "sku" = 'VIS-SR-30' OR "pancakeId" = 'seed-VIS-SR-30');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfuw9k2000bw1vfnqnknvfc', 'seed-FUWA-LD-2L', 'p-fuwa-laundry', 'FUWA-LD-2L', '2L', '{"size":"2L"}'::jsonb, 210000, NULL, NULL, NULL, 150, TRUE, 2100
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfuw9k2000bw1vfnqnknvfc' OR "sku" = 'FUWA-LD-2L' OR "pancakeId" = 'seed-FUWA-LD-2L');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfuw9k5000dw1vf2tdedsu4', 'seed-POLANG-BW-500', 'p-polang-bodywash', 'POLANG-BW-500', '500ml', '{"size":"500ml","scent":"sả chanh"}'::jsonb, 175000, NULL, NULL, NULL, 90, TRUE, 560
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfuw9k5000dw1vf2tdedsu4' OR "sku" = 'POLANG-BW-500' OR "pancakeId" = 'seed-POLANG-BW-500');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfuw9ka000fw1vfu3yl2jph', 'seed-VIS-CR-100', 'p-visante-cream', 'VIS-CR-100', '100ml', '{"size":"100ml"}'::jsonb, 290000, NULL, NULL, NULL, 45, TRUE, 160
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfuw9ka000fw1vfu3yl2jph' OR "sku" = 'VIS-CR-100' OR "pancakeId" = 'seed-VIS-CR-100');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv2cky0003zxpl45lh4ggm', 'seed-VIS-SR-50', 'p-visante-serum', 'VIS-SR-50', '50ml', '{"size":"50ml"}'::jsonb, 460000, NULL, NULL, NULL, 30, TRUE, 130
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv2cky0003zxpl45lh4ggm' OR "sku" = 'VIS-SR-50' OR "pancakeId" = 'seed-VIS-SR-50');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv2cl90007zxpllq9mw8h1', 'seed-VIS-CL-300', 'p-visante-cleanser', 'VIS-CL-300', '300ml', '{"size":"300ml"}'::jsonb, 180000, 155000, NULL, NULL, 110, TRUE, 330
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv2cl90007zxpllq9mw8h1' OR "sku" = 'VIS-CL-300' OR "pancakeId" = 'seed-VIS-CL-300');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv2cle0009zxpljhaxy9ny', 'seed-VIS-SUN-50', 'p-visante-sunscreen', 'VIS-SUN-50', '50ml', '{"spf":"SPF50+","size":"50ml"}'::jsonb, 345000, NULL, NULL, NULL, 70, TRUE, 95
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv2cle0009zxpljhaxy9ny' OR "sku" = 'VIS-SUN-50' OR "pancakeId" = 'seed-VIS-SUN-50');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv2clh000bzxpl4iysg6k0', 'seed-VIS-MASK-1', 'p-visante-mask', 'VIS-MASK-1', '1 miếng', '{"type":"sheet"}'::jsonb, 25000, NULL, NULL, NULL, 400, TRUE, 30
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv2clh000bzxpl4iysg6k0' OR "sku" = 'VIS-MASK-1' OR "pancakeId" = 'seed-VIS-MASK-1');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv2clk000dzxpl77y1nlvo', 'seed-VIS-LIP-4', 'p-visante-lipbalm', 'VIS-LIP-4', '4g', '{"size":"4g"}'::jsonb, 95000, 79000, NULL, NULL, 180, TRUE, 20
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv2clk000dzxpl77y1nlvo' OR "sku" = 'VIS-LIP-4' OR "pancakeId" = 'seed-VIS-LIP-4');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv2cly000lzxplzmfsw4ze', 'seed-POLANG-GG-100', 'p-polang-ginger', 'POLANG-GG-100', '100ml', '{"size":"100ml"}'::jsonb, 135000, 115000, NULL, NULL, 140, TRUE, 150
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv2cly000lzxplzmfsw4ze' OR "sku" = 'POLANG-GG-100' OR "pancakeId" = 'seed-POLANG-GG-100');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv2cm2000nzxplhcpee2k8', 'seed-POLANG-LG-10', 'p-polang-lemongrass', 'POLANG-LG-10', '10ml', '{"size":"10ml"}'::jsonb, 110000, NULL, NULL, NULL, 220, TRUE, 40
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv2cm2000nzxplhcpee2k8' OR "sku" = 'POLANG-LG-10' OR "pancakeId" = 'seed-POLANG-LG-10');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv2cm6000pzxplj5ipj3dz', 'seed-POLANG-FM-150', 'p-polang-facemist', 'POLANG-FM-150', '150ml', '{"size":"150ml"}'::jsonb, 145000, NULL, NULL, NULL, 95, TRUE, 200
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv2cm6000pzxplj5ipj3dz' OR "sku" = 'POLANG-FM-150' OR "pancakeId" = 'seed-POLANG-FM-150');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv2cmj000xzxplrbaoikwf', 'seed-FUWA-FL-2L', 'p-fuwa-floor', 'FUWA-FL-2L', '2L', '{"size":"2L"}'::jsonb, 165000, 139000, NULL, NULL, 120, TRUE, 2100
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv2cmj000xzxplrbaoikwf' OR "sku" = 'FUWA-FL-2L' OR "pancakeId" = 'seed-FUWA-FL-2L');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv2cmm000zzxplbqlf8d47', 'seed-FUWA-HW-500', 'p-fuwa-handwash', 'FUWA-HW-500', '500ml', '{"size":"500ml"}'::jsonb, 89000, NULL, NULL, NULL, 260, TRUE, 540
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv2cmm000zzxplbqlf8d47' OR "sku" = 'FUWA-HW-500' OR "pancakeId" = 'seed-FUWA-HW-500');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv2cmq0011zxpl67fkxph0', 'seed-FUWA-BT-500', 'p-fuwa-bottle', 'FUWA-BT-500', '500ml', '{"size":"500ml"}'::jsonb, 135000, NULL, NULL, NULL, 130, TRUE, 540
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv2cmq0011zxpl67fkxph0' OR "sku" = 'FUWA-BT-500' OR "pancakeId" = 'seed-FUWA-BT-500');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv2cmu0013zxpltkclxi2l', 'seed-COBOTE-TR-50', 'p-cobote-tram', 'COBOTE-TR-50', '50ml', '{"size":"50ml"}'::jsonb, 89000, NULL, NULL, NULL, 300, TRUE, 80
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv2cmu0013zxpltkclxi2l' OR "sku" = 'COBOTE-TR-50' OR "pancakeId" = 'seed-COBOTE-TR-50');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv2cmx0015zxpliyqff23n', 'seed-COBOTE-WS-250', 'p-cobote-wash', 'COBOTE-WS-250', '250ml', '{"size":"250ml"}'::jsonb, 155000, 132000, NULL, NULL, 110, TRUE, 290
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv2cmx0015zxpliyqff23n' OR "sku" = 'COBOTE-WS-250' OR "pancakeId" = 'seed-COBOTE-WS-250');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv2cn10017zxpl3ga9aqov', 'seed-COBOTE-PW-100', 'p-cobote-powder', 'COBOTE-PW-100', '100g', '{"size":"100g"}'::jsonb, 79000, NULL, NULL, NULL, 160, TRUE, 130
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv2cn10017zxpl3ga9aqov' OR "sku" = 'COBOTE-PW-100' OR "pancakeId" = 'seed-COBOTE-PW-100');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv2cn40019zxpl2qpbbuz9', 'seed-COBOTE-DC-50', 'p-cobote-diapercream', 'COBOTE-DC-50', '50g', '{"size":"50g"}'::jsonb, 119000, NULL, NULL, NULL, 140, TRUE, 70
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv2cn40019zxpl2qpbbuz9' OR "sku" = 'COBOTE-DC-50' OR "pancakeId" = 'seed-COBOTE-DC-50');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv2cn8001bzxplgwqxryd7', 'seed-LP-ARA-250', 'p-leplateau-arabica', 'LP-ARA-250', '250g · nguyên hạt', '{"grind":"nguyên hạt","weight":"250g"}'::jsonb, 185000, NULL, NULL, NULL, 90, TRUE, 270
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv2cn8001bzxplgwqxryd7' OR "sku" = 'LP-ARA-250' OR "pancakeId" = 'seed-LP-ARA-250');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv2cna001dzxplgpkfevuc', 'seed-LP-ARA-250-F', 'p-leplateau-arabica', 'LP-ARA-250-F', '250g · xay pha phin', '{"grind":"pha phin","weight":"250g"}'::jsonb, 185000, NULL, NULL, NULL, 70, TRUE, 270
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv2cna001dzxplgpkfevuc' OR "sku" = 'LP-ARA-250-F' OR "pancakeId" = 'seed-LP-ARA-250-F');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv2cne001fzxplyiuh0ubv', 'seed-LP-ROB-250', 'p-leplateau-robusta', 'LP-ROB-250', '250g', '{"weight":"250g"}'::jsonb, 145000, 125000, NULL, NULL, 120, TRUE, 270
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv2cne001fzxplyiuh0ubv' OR "sku" = 'LP-ROB-250' OR "pancakeId" = 'seed-LP-ROB-250');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv2cnh001hzxplrhjcbe6i', 'seed-LP-DRIP-10', 'p-leplateau-drip', 'LP-DRIP-10', 'Hộp 10 gói', '{"count":"10"}'::jsonb, 95000, NULL, NULL, NULL, 200, TRUE, 130
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv2cnh001hzxplrhjcbe6i' OR "sku" = 'LP-DRIP-10' OR "pancakeId" = 'seed-LP-DRIP-10');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv2cnk001jzxpl47uenljj', 'seed-LP-CB-5', 'p-leplateau-coldbrew', 'LP-CB-5', 'Hộp 5 túi', '{"count":"5"}'::jsonb, 120000, NULL, NULL, NULL, 85, TRUE, 180
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv2cnk001jzxpl47uenljj' OR "sku" = 'LP-CB-5' OR "pancakeId" = 'seed-LP-CB-5');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv2cnp001lzxpldj0hlwq2', 'seed-BHN-HN-500', 'p-bhnong-honey', 'BHN-HN-500', 'Chai 500ml', '{"size":"500ml"}'::jsonb, 260000, NULL, NULL, NULL, 80, TRUE, 720
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv2cnp001lzxpldj0hlwq2' OR "sku" = 'BHN-HN-500' OR "pancakeId" = 'seed-BHN-HN-500');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv2cns001nzxplvuhm8hyq', 'seed-BHN-CW-500', 'p-bhnong-cashew', 'BHN-CW-500', '500g', '{"weight":"500g"}'::jsonb, 180000, 159000, NULL, NULL, 150, TRUE, 540
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv2cns001nzxplvuhm8hyq' OR "sku" = 'BHN-CW-500' OR "pancakeId" = 'seed-BHN-CW-500');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv2cnv001pzxpljb96x5t3', 'seed-BHN-PP-200', 'p-bhnong-pepper', 'BHN-PP-200', '200g', '{"weight":"200g"}'::jsonb, 95000, NULL, NULL, NULL, 200, TRUE, 230
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv2cnv001pzxpljb96x5t3' OR "sku" = 'BHN-PP-200' OR "pancakeId" = 'seed-BHN-PP-200');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv2cny001rzxplrwccxk9l', 'seed-BHN-TEA-20', 'p-bhnong-tea', 'BHN-TEA-20', 'Hộp 20 túi', '{"count":"20"}'::jsonb, 85000, NULL, NULL, NULL, 180, TRUE, 80
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv2cny001rzxplrwccxk9l' OR "sku" = 'BHN-TEA-20' OR "pancakeId" = 'seed-BHN-TEA-20');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv2co1001tzxplz8u0kdgs', 'seed-SOK-RC-1KG', 'p-sokfram-rice', 'SOK-RC-1KG', '1kg', '{"weight":"1kg"}'::jsonb, 75000, NULL, NULL, NULL, 220, TRUE, 1050
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv2co1001tzxplz8u0kdgs' OR "sku" = 'SOK-RC-1KG' OR "pancakeId" = 'seed-SOK-RC-1KG');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv2co7001vzxplf8ka2cqo', 'seed-SOK-CO-500', 'p-sokfram-coconut', 'SOK-CO-500', '500ml', '{"size":"500ml"}'::jsonb, 130000, 110000, NULL, NULL, 140, TRUE, 560
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv2co7001vzxplf8ka2cqo' OR "sku" = 'SOK-CO-500' OR "pancakeId" = 'seed-SOK-CO-500');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv2coa001xzxpltjepz3ee', 'seed-SOK-CT-150', 'p-sokfram-centella', 'SOK-CT-150', '150g', '{"weight":"150g"}'::jsonb, 99000, NULL, NULL, NULL, 160, TRUE, 180
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv2coa001xzxpltjepz3ee' OR "sku" = 'SOK-CT-150' OR "pancakeId" = 'seed-SOK-CT-150');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv2cod001zzxpl11l7qcbj', 'seed-SOK-GR-400', 'p-sokfram-granola', 'SOK-GR-400', '400g', '{"weight":"400g"}'::jsonb, 140000, NULL, NULL, NULL, 120, TRUE, 440
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv2cod001zzxpl11l7qcbj' OR "sku" = 'SOK-GR-400' OR "pancakeId" = 'seed-SOK-GR-400');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv2cog0021zxpl1nny40zl', 'seed-HEC-CL-80', 'p-hector-clay', 'HEC-CL-80', '80g', '{"size":"80g"}'::jsonb, 160000, NULL, NULL, NULL, 130, TRUE, 110
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv2cog0021zxpl1nny40zl' OR "sku" = 'HEC-CL-80' OR "pancakeId" = 'seed-HEC-CL-80');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv2cok0023zxpldwfrc7q2', 'seed-HEC-FW-120', 'p-hector-facewash', 'HEC-FW-120', '120ml', '{"size":"120ml"}'::jsonb, 145000, 119000, NULL, NULL, 150, TRUE, 150
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv2cok0023zxpldwfrc7q2' OR "sku" = 'HEC-FW-120' OR "pancakeId" = 'seed-HEC-FW-120');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv2coo0025zxplxiucn77n', 'seed-HEC-SH-300', 'p-hector-shampoo', 'HEC-SH-300', '300ml', '{"size":"300ml"}'::jsonb, 135000, NULL, NULL, NULL, 140, TRUE, 330
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv2coo0025zxplxiucn77n' OR "sku" = 'HEC-SH-300' OR "pancakeId" = 'seed-HEC-SH-300');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv2cor0027zxplzj1loywb', 'seed-HEC-DEO-50', 'p-hector-deo', 'HEC-DEO-50', '50ml', '{"size":"50ml"}'::jsonb, 99000, NULL, NULL, NULL, 200, TRUE, 70
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv2cor0027zxplzj1loywb' OR "sku" = 'HEC-DEO-50' OR "pancakeId" = 'seed-HEC-DEO-50');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv3q5t0029cgcob3flmcuv', 'seed-VIS-VITC-20', 'p-visante-vitc', 'VIS-VITC-20', '20ml', '{"size":"20ml"}'::jsonb, 380000, 329000, NULL, NULL, 55, TRUE, 70
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv3q5t0029cgcob3flmcuv' OR "sku" = 'VIS-VITC-20' OR "pancakeId" = 'seed-VIS-VITC-20');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv3q5z002bcgcok2ziwtlw', 'seed-VIS-EYE-15', 'p-visante-eye', 'VIS-EYE-15', '15ml', '{"size":"15ml"}'::jsonb, 295000, NULL, NULL, NULL, 60, TRUE, 50
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv3q5z002bcgcok2ziwtlw' OR "sku" = 'VIS-EYE-15' OR "pancakeId" = 'seed-VIS-EYE-15');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv3q63002dcgcojpljp11u', 'seed-POLANG-HO-50', 'p-polang-hairoil', 'POLANG-HO-50', '50ml', '{"size":"50ml"}'::jsonb, 125000, NULL, NULL, NULL, 110, TRUE, 80
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv3q63002dcgcojpljp11u' OR "sku" = 'POLANG-HO-50' OR "pancakeId" = 'seed-POLANG-HO-50');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv3q67002fcgcoxpqsxpb4', 'seed-FUWA-GL-500', 'p-fuwa-glass', 'FUWA-GL-500', '500ml', '{"size":"500ml"}'::jsonb, 79000, NULL, NULL, NULL, 170, TRUE, 540
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv3q67002fcgcoxpqsxpb4' OR "sku" = 'FUWA-GL-500' OR "pancakeId" = 'seed-FUWA-GL-500');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv3q6a002hcgco5nxp0lzl', 'seed-COBOTE-MS-100', 'p-cobote-massage', 'COBOTE-MS-100', '100ml', '{"size":"100ml"}'::jsonb, 109000, NULL, NULL, NULL, 120, TRUE, 130
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv3q6a002hcgco5nxp0lzl' OR "sku" = 'COBOTE-MS-100' OR "pancakeId" = 'seed-COBOTE-MS-100');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv3q6e002jcgcojneu7uab', 'seed-LP-INS-12', 'p-leplateau-instant', 'LP-INS-12', 'Hộp 12 gói', '{"count":"12"}'::jsonb, 89000, 75000, NULL, NULL, 190, TRUE, 320
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv3q6e002jcgcojneu7uab' OR "sku" = 'LP-INS-12' OR "pancakeId" = 'seed-LP-INS-12');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv3q6h002lcgcou94v9rfl', 'seed-BHN-CGL-100', 'p-bhnong-cagaileo', 'BHN-CGL-100', 'Hũ 100g', '{"size":"100g"}'::jsonb, 220000, NULL, NULL, NULL, 70, TRUE, 160
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv3q6h002lcgcou94v9rfl' OR "sku" = 'BHN-CGL-100' OR "pancakeId" = 'seed-BHN-CGL-100');
INSERT INTO variations ("id", "pancakeId", "productId", "sku", "name", "attributes", "retailPrice", "salePrice", "dealerPrices", "affiliateRate", "stock", "isActive", "weight")
SELECT 'cmqfv3q6m002ncgco4pgk0rh7', 'seed-SOK-CH-500', 'p-sokfram-chia', 'SOK-CH-500', '500g', '{"weight":"500g"}'::jsonb, 115000, NULL, NULL, NULL, 150, TRUE, 540
WHERE NOT EXISTS (SELECT 1 FROM variations WHERE "id" = 'cmqfv3q6m002ncgco4pgk0rh7' OR "sku" = 'SOK-CH-500' OR "pancakeId" = 'seed-SOK-CH-500');

-- coupons: 3 dòng
INSERT INTO coupons ("id", "code", "type", "value", "minOrder", "maxDiscount", "startAt", "endAt", "usageLimit", "perUserLimit", "applyTo", "isStackable", "scope", "scopeMeta")
SELECT 'cmqfuw9l0000gw1vf8f2wozy0', 'WELCOME30', 'AMOUNT', 30000, 199000, NULL, '2025-12-31T17:00:00.000Z', '2026-12-31T17:00:00.000Z', NULL, 1, NULL, FALSE, 'PUBLIC', NULL
WHERE NOT EXISTS (SELECT 1 FROM coupons WHERE "code" = 'WELCOME30');
INSERT INTO coupons ("id", "code", "type", "value", "minOrder", "maxDiscount", "startAt", "endAt", "usageLimit", "perUserLimit", "applyTo", "isStackable", "scope", "scopeMeta")
SELECT 'cmqfv2cpl0029zxplw4kcnaji', 'FREESHIP', 'FREESHIP', 0, 99000, NULL, '2025-12-31T17:00:00.000Z', '2026-12-31T17:00:00.000Z', NULL, 3, NULL, FALSE, 'PUBLIC', NULL
WHERE NOT EXISTS (SELECT 1 FROM coupons WHERE "code" = 'FREESHIP');
INSERT INTO coupons ("id", "code", "type", "value", "minOrder", "maxDiscount", "startAt", "endAt", "usageLimit", "perUserLimit", "applyTo", "isStackable", "scope", "scopeMeta")
SELECT 'cmqfv2cpn002azxplta2xvgp8', 'XANH10', 'PERCENT', 10, 250000, 50000, '2025-12-31T17:00:00.000Z', '2026-12-31T17:00:00.000Z', NULL, 2, NULL, FALSE, 'PUBLIC', NULL
WHERE NOT EXISTS (SELECT 1 FROM coupons WHERE "code" = 'XANH10');

-- Backfill ảnh cho sản phẩm seed đã tồn tại nhưng thiếu ảnh (chỉ chạm dòng thiếu ảnh).
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-cao-ca-gai-leo-bhnong/800/800', images=ARRAY['https://picsum.photos/seed/tubu-cao-ca-gai-leo-bhnong/800/800']::text[] WHERE id='p-bhnong-cagaileo' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-hat-dieu-rang-moc-bhnong/800/800', images=ARRAY['https://picsum.photos/seed/tubu-hat-dieu-rang-moc-bhnong/800/800']::text[] WHERE id='p-bhnong-cashew' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-mat-ong-rung-bhnong/800/800', images=ARRAY['https://picsum.photos/seed/tubu-mat-ong-rung-bhnong/800/800']::text[] WHERE id='p-bhnong-honey' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-tieu-den-bhnong/800/800', images=ARRAY['https://picsum.photos/seed/tubu-tieu-den-bhnong/800/800']::text[] WHERE id='p-bhnong-pepper' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-tra-thao-moc-bhnong/800/800', images=ARRAY['https://picsum.photos/seed/tubu-tra-thao-moc-bhnong/800/800']::text[] WHERE id='p-bhnong-tea' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-kem-chong-ham-cobote/800/800', images=ARRAY['https://picsum.photos/seed/tubu-kem-chong-ham-cobote/800/800']::text[] WHERE id='p-cobote-diapercream' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-dau-massage-be-cobote/800/800', images=ARRAY['https://picsum.photos/seed/tubu-dau-massage-be-cobote/800/800']::text[] WHERE id='p-cobote-massage' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-phan-rom-thao-duoc-cobote/800/800', images=ARRAY['https://picsum.photos/seed/tubu-phan-rom-thao-duoc-cobote/800/800']::text[] WHERE id='p-cobote-powder' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-dau-tram-be-cobote/800/800', images=ARRAY['https://picsum.photos/seed/tubu-dau-tram-be-cobote/800/800']::text[] WHERE id='p-cobote-tram' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-nuoc-tam-goi-be-cobote/800/800', images=ARRAY['https://picsum.photos/seed/tubu-nuoc-tam-goi-be-cobote/800/800']::text[] WHERE id='p-cobote-wash' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-nuoc-rua-binh-sua-fuwa3e/800/800', images=ARRAY['https://picsum.photos/seed/tubu-nuoc-rua-binh-sua-fuwa3e/800/800']::text[] WHERE id='p-fuwa-bottle' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-nuoc-rua-chen-fuwa3e/800/800', images=ARRAY['https://picsum.photos/seed/tubu-nuoc-rua-chen-fuwa3e/800/800']::text[] WHERE id='p-fuwa-dishwash' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-nuoc-lau-san-fuwa3e/800/800', images=ARRAY['https://picsum.photos/seed/tubu-nuoc-lau-san-fuwa3e/800/800']::text[] WHERE id='p-fuwa-floor' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-nuoc-lau-kinh-fuwa3e/800/800', images=ARRAY['https://picsum.photos/seed/tubu-nuoc-lau-kinh-fuwa3e/800/800']::text[] WHERE id='p-fuwa-glass' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-nuoc-rua-tay-fuwa3e/800/800', images=ARRAY['https://picsum.photos/seed/tubu-nuoc-rua-tay-fuwa3e/800/800']::text[] WHERE id='p-fuwa-handwash' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-nuoc-giat-fuwa3e/800/800', images=ARRAY['https://picsum.photos/seed/tubu-nuoc-giat-fuwa3e/800/800']::text[] WHERE id='p-fuwa-laundry' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-sap-vuot-toc-hector/800/800', images=ARRAY['https://picsum.photos/seed/tubu-sap-vuot-toc-hector/800/800']::text[] WHERE id='p-hector-clay' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-lan-khu-mui-hector/800/800', images=ARRAY['https://picsum.photos/seed/tubu-lan-khu-mui-hector/800/800']::text[] WHERE id='p-hector-deo' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-sua-rua-mat-than-tre-hector/800/800', images=ARRAY['https://picsum.photos/seed/tubu-sua-rua-mat-than-tre-hector/800/800']::text[] WHERE id='p-hector-facewash' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-dau-goi-bac-ha-hector/800/800', images=ARRAY['https://picsum.photos/seed/tubu-dau-goi-bac-ha-hector/800/800']::text[] WHERE id='p-hector-shampoo' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-arabica-cau-dat-le-plateau/800/800', images=ARRAY['https://picsum.photos/seed/tubu-arabica-cau-dat-le-plateau/800/800']::text[] WHERE id='p-leplateau-arabica' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-cold-brew-tui-loc-le-plateau/800/800', images=ARRAY['https://picsum.photos/seed/tubu-cold-brew-tui-loc-le-plateau/800/800']::text[] WHERE id='p-leplateau-coldbrew' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-ca-phe-phin-giay-le-plateau/800/800', images=ARRAY['https://picsum.photos/seed/tubu-ca-phe-phin-giay-le-plateau/800/800']::text[] WHERE id='p-leplateau-drip' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-ca-phe-sua-hoa-tan-le-plateau/800/800', images=ARRAY['https://picsum.photos/seed/tubu-ca-phe-sua-hoa-tan-le-plateau/800/800']::text[] WHERE id='p-leplateau-instant' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-robusta-honey-le-plateau/800/800', images=ARRAY['https://picsum.photos/seed/tubu-robusta-honey-le-plateau/800/800']::text[] WHERE id='p-leplateau-robusta' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-sua-tam-sa-po-lang/800/800', images=ARRAY['https://picsum.photos/seed/tubu-sua-tam-sa-po-lang/800/800']::text[] WHERE id='p-polang-bodywash' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-xit-khoang-hoa-hong-po-lang/800/800', images=ARRAY['https://picsum.photos/seed/tubu-xit-khoang-hoa-hong-po-lang/800/800']::text[] WHERE id='p-polang-facemist' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-dau-gung-po-lang/800/800', images=ARRAY['https://picsum.photos/seed/tubu-dau-gung-po-lang/800/800']::text[] WHERE id='p-polang-ginger' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-dau-duong-toc-bo-ket-po-lang/800/800', images=ARRAY['https://picsum.photos/seed/tubu-dau-duong-toc-bo-ket-po-lang/800/800']::text[] WHERE id='p-polang-hairoil' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-tinh-dau-sa-chanh-po-lang/800/800', images=ARRAY['https://picsum.photos/seed/tubu-tinh-dau-sa-chanh-po-lang/800/800']::text[] WHERE id='p-polang-lemongrass' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-dau-goi-buoi-po-lang/800/800', images=ARRAY['https://picsum.photos/seed/tubu-dau-goi-buoi-po-lang/800/800']::text[] WHERE id='p-polang-shampoo' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-bot-rau-ma-sokfram/800/800', images=ARRAY['https://picsum.photos/seed/tubu-bot-rau-ma-sokfram/800/800']::text[] WHERE id='p-sokfram-centella' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-hat-chia-uc-sokfram/800/800', images=ARRAY['https://picsum.photos/seed/tubu-hat-chia-uc-sokfram/800/800']::text[] WHERE id='p-sokfram-chia' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-dau-dua-ep-lanh-sokfram/800/800', images=ARRAY['https://picsum.photos/seed/tubu-dau-dua-ep-lanh-sokfram/800/800']::text[] WHERE id='p-sokfram-coconut' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-granola-hat-sokfram/800/800', images=ARRAY['https://picsum.photos/seed/tubu-granola-hat-sokfram/800/800']::text[] WHERE id='p-sokfram-granola' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-gao-lut-huyet-rong-sokfram/800/800', images=ARRAY['https://picsum.photos/seed/tubu-gao-lut-huyet-rong-sokfram/800/800']::text[] WHERE id='p-sokfram-rice' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-nuoc-tay-trang-rau-ma-visante/800/800', images=ARRAY['https://picsum.photos/seed/tubu-nuoc-tay-trang-rau-ma-visante/800/800']::text[] WHERE id='p-visante-cleanser' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-kem-duong-ba-bau-visante/800/800', images=ARRAY['https://picsum.photos/seed/tubu-kem-duong-ba-bau-visante/800/800']::text[] WHERE id='p-visante-cream' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-kem-mat-rau-ma-visante/800/800', images=ARRAY['https://picsum.photos/seed/tubu-kem-mat-rau-ma-visante/800/800']::text[] WHERE id='p-visante-eye' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-son-duong-gac-visante/800/800', images=ARRAY['https://picsum.photos/seed/tubu-son-duong-gac-visante/800/800']::text[] WHERE id='p-visante-lipbalm' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-mat-na-rau-ma-visante/800/800', images=ARRAY['https://picsum.photos/seed/tubu-mat-na-rau-ma-visante/800/800']::text[] WHERE id='p-visante-mask' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-serum-duong-am-visante/800/800', images=ARRAY['https://picsum.photos/seed/tubu-serum-duong-am-visante/800/800']::text[] WHERE id='p-visante-serum' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-kem-chong-nang-khoang-visante/800/800', images=ARRAY['https://picsum.photos/seed/tubu-kem-chong-nang-khoang-visante/800/800']::text[] WHERE id='p-visante-sunscreen' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
UPDATE products SET thumbnail='https://picsum.photos/seed/tubu-tinh-chat-vitamin-c-visante/800/800', images=ARRAY['https://picsum.photos/seed/tubu-tinh-chat-vitamin-c-visante/800/800']::text[] WHERE id='p-visante-vitc' AND (thumbnail IS NULL OR thumbnail='' OR array_length(images,1) IS NULL);
